name: CI for all branches

on: [push]

jobs:

  lint:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Lint the application
      run: npm install
      run: npm run lint
      
      
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test the application
      run: npm run test

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        ORG: bjoberg
        REPO: portfolio-dashboard
      run: docker build . --file Dockerfile --tag $ORG/$REPO:$(date +%s)
